"""
Phase 2 - AI Triage Engine
Uses LLM to analyze JS snippets and auto-generate bug bounty reports.
"""
import os
import json
from typing import List, Dict, Optional
from dotenv import load_dotenv

load_dotenv()


class AITriageEngine:
    """
    Uses OpenAI GPT to:
    1. Analyze JS code snippets for potential logic flaws.
    2. Generate professional HackerOne/Bugcrowd formatted reports.
    3. Explain why a finding matters in plain English.
    """

    def __init__(self):
        self.api_key = os.getenv("OPENAI_API_KEY", "")
        self.model = "gpt-4o-mini"  # Cost-efficient for bulk analysis
        self._client = None

    def _get_client(self):
        if not self.api_key:
            return None
        if not self._client:
            try:
                from openai import OpenAI
                self._client = OpenAI(api_key=self.api_key)
            except ImportError:
                return None
        return self._client

    # ── JS Code Analysis ───────────────────────────────────────────────────

    def analyze_js_snippet(self, code: str, source_url: str = "") -> Optional[Dict]:
        """Ask GPT to review a JS snippet for security issues."""
        client = self._get_client()
        if not client or not code.strip():
            return None

        prompt = f"""You are a senior bug bounty security researcher. Analyze this JavaScript code snippet for security vulnerabilities.

Source URL: {source_url}

Code:
```js
{code[:3000]}
```

Look specifically for:
- Authentication bypasses
- Hardcoded secrets or API keys
- Dangerous sinks (innerHTML, eval, document.write)
- Sensitive data exposure
- Business logic flaws
- Client-side authorization checks

Respond in JSON with this structure:
{{
  "has_issues": true/false,
  "severity": "critical|high|medium|low|info",
  "findings": [
    {{
      "type": "Vulnerability type",
      "description": "What the issue is",
      "line_hint": "relevant code",
      "impact": "What an attacker could do",
      "confidence": 0.0-1.0
    }}
  ]
}}"""

        try:
            resp = client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                response_format={"type": "json_object"},
                temperature=0.1,
            )
            data = json.loads(resp.choices[0].message.content)
            if data.get("has_issues"):
                for f in data.get("findings", []):
                    f["source_url"] = source_url
                    f["type"] = f"AI: {f.get('type', 'Unknown')}"
            return data
        except Exception:
            return None

    # ── Report Generation ─────────────────────────────────────────────────

    def generate_report(self, finding: Dict, target: str) -> Optional[str]:
        """Generate a ready-to-submit bug bounty report for a finding."""
        client = self._get_client()
        if not client:
            return self._template_report(finding, target)

        prompt = f"""You are a professional bug bounty hunter writing a report for HackerOne/Bugcrowd.
Write a clear, concise, professional bug report for the following finding.

Target: {target}
Finding Type: {finding.get('type')}
Severity: {finding.get('severity')}
URL: {finding.get('url')}
Evidence: {finding.get('evidence', 'N/A')}
Additional context: {json.dumps(finding, default=str)[:500]}

Format the report with:
# [Vulnerability Type] in [Component]
## Summary
## Steps to Reproduce
## Impact
## Remediation
## Severity Justification"""

        try:
            resp = client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3,
            )
            return resp.choices[0].message.content
        except Exception:
            return self._template_report(finding, target)

    def _template_report(self, finding: Dict, target: str) -> str:
        """Fallback Markdown report without LLM."""
        return f"""# {finding.get('type', 'Vulnerability')} in {target}

## Summary
A {finding.get('severity', 'medium').upper()} severity {finding.get('type', 'vulnerability')} was found at:
`{finding.get('url', target)}`

## Why It Matters
{finding.get('why_it_matters', 'This finding may expose sensitive functionality.')}

## Steps to Reproduce
1. Navigate to: `{finding.get('url', target)}`
2. Observe: {finding.get('evidence', 'See evidence below')}
3. {finding.get('suggested_next_step', 'Confirm behaviour manually.')}

## Impact
Risk Score: **{finding.get('risk_score', 'N/A')}/10**
Confidence: **{finding.get('confidence', 'N/A')}**

## Remediation
Implement proper server-side validation, access controls, and security headers.

---
*Generated by Bug Bounty Recon Platform*
"""

    # ── Batch Analysis ─────────────────────────────────────────────────────

    def triage_findings(self, findings: List[Dict]) -> List[Dict]:
        """Add AI explanation to top high-confidence findings."""
        client = self._get_client()
        enriched = []
        for f in findings:
            if f.get("confidence", 0) >= 0.7 and client:
                # Only call AI for high-confidence findings to save cost
                report = self.generate_report(f, f.get("url", ""))
                f["ai_report"] = report
            else:
                f["ai_report"] = self._template_report(f, f.get("url", ""))
            enriched.append(f)
        return enriched
